from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 314)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Flag_of_Interslavic.svg.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Prefiks_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.Prefiks_lineedit.setGeometry(QtCore.QRect(70, 30, 61, 16))
        self.Prefiks_lineedit.setObjectName("Prefiks_lineedit")
        self.Keyboard_label = QtWidgets.QLabel(self.centralwidget)
        self.Keyboard_label.setGeometry(QtCore.QRect(10, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.Keyboard_label.setFont(font)
        self.Keyboard_label.setObjectName("Keyboard_label")
        self.Prefiks_chekbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Prefiks_chekbox.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.Prefiks_chekbox.setObjectName("Prefiks_chekbox")
        self.Alt_key_chekbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Alt_key_chekbox.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.Alt_key_chekbox.setObjectName("Alt_key_chekbox")
        self.Ctrl_key_chekbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Ctrl_key_chekbox.setGeometry(QtCore.QRect(10, 70, 70, 17))
        self.Ctrl_key_chekbox.setObjectName("Ctrl_key_chekbox")
        self.Shift_key_chekbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Shift_key_chekbox.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.Shift_key_chekbox.setObjectName("Shift_key_chekbox")
        self.Aktiva_label = QtWidgets.QLabel(self.centralwidget)
        self.Aktiva_label.setGeometry(QtCore.QRect(10, 120, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.Aktiva_label.setFont(font)
        self.Aktiva_label.setObjectName("Aktiva_label")
        self.Always_aktive_chekbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Always_aktive_chekbox.setGeometry(QtCore.QRect(10, 140, 181, 17))
        self.Always_aktive_chekbox.setObjectName("Always_aktive_chekbox")
        self.Always_autostart_chekbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Always_autostart_chekbox.setGeometry(QtCore.QRect(10, 160, 231, 17))
        self.Always_autostart_chekbox.setObjectName("Always_autostart_chekbox")
        self.Switch_label = QtWidgets.QLabel(self.centralwidget)
        self.Switch_label.setGeometry(QtCore.QRect(10, 190, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.Switch_label.setFont(font)
        self.Switch_label.setObjectName("Switch_label")
        self.Switch_programm_chekbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Switch_programm_chekbox.setGeometry(QtCore.QRect(10, 210, 211, 17))
        self.Switch_programm_chekbox.setObjectName("Switch_programm_chekbox")
        self.Ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.Ok_button.setGeometry(QtCore.QRect(190, 250, 75, 23))
        self.Ok_button.setObjectName("Ok_button")
        self.Reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.Reset_button.setGeometry(QtCore.QRect(10, 250, 171, 21))
        self.Reset_button.setObjectName("Reset_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interslavic Keyboard"))
        self.Keyboard_label.setText(_translate("MainWindow", "Tipkovnica \\ Типковница"))
        self.Prefiks_chekbox.setText(_translate("MainWindow", "Prefiks:"))
        self.Alt_key_chekbox.setText(_translate("MainWindow", "Alt + key"))
        self.Ctrl_key_chekbox.setText(_translate("MainWindow", "Ctrl + key"))
        self.Shift_key_chekbox.setText(_translate("MainWindow", "Shift + key"))
        self.Aktiva_label.setText(_translate("MainWindow", "Početi \\ Почети"))
        self.Always_aktive_chekbox.setText(_translate("MainWindow", "početi aktivno \\ почети активно "))
        self.Always_autostart_chekbox.setText(_translate("MainWindow", "početi avtomatično \\ почети автоматично"))
        self.Switch_label.setText(_translate("MainWindow", "Prěključati \\ Прєкључати"))
        self.Switch_programm_chekbox.setText(_translate("MainWindow", "Programa aktivny \\ Програма актвины"))
        self.Ok_button.setText(_translate("MainWindow", "ОК"))
        self.Reset_button.setText(_translate("MainWindow", "prědustavjenje \\ прєдуставјенје\n"
""))
